# Generated by Django 4.2.9 on 2024-02-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Easy"),
                            (2, "Medium"),
                            (3, "Hard"),
                            (4, "Very hard"),
                        ]
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
