# Generated by Django 4.2.9 on 2024-02-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_board_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="title",
            field=models.CharField(default="", max_length=20),
        ),
    ]
